# Generated by Django 4.2.1 on 2023-05-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hinded', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hinded',
            name='nimi',
            field=models.CharField(default='Kontrolltöö', max_length=100),
        ),
    ]
