# Generated by Django 4.2.1 on 2023-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hinded', '0003_alter_hinded_kirjeldus_alter_isikuhinne_markmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='isik',
            name='kood',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
